name: Docker Image CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone Code
      run: git clone https://github.com/liupengzhouyi/GrandetServer.git
    
    - name: show path
      run: pwd

    - name: show files
      run: ls

    - name: show files print
      run: echo "$(ls -l)"

    - name: input Project
      run: cd GrandetServer
      
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t grandet_server .
      
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag grandet_server:$(date +%s)

    - name: show path
      run: pwd
